apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-api
  namespace: products
spec:
  replicas: 1

  selector:
    matchLabels:
      app: nestjs-api

  template:
    metadata:
      labels:
        app: nestjs-api

    spec:
      containers:
        - name: nestjs-api

          image: jrgonzalezo/nest-products-api:1.0

          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          env:
            - name: DB_HOST
              value: "192.168.20.24"

            - name: DB_PORT
              value: "5432"

            - name: DB_USER
              value: "postgres"

            - name: DB_PASSWORD
              value: "12345"

            - name: DB_NAME
              value: "productsdb"

            - name: API_PORT
              value: "3001"