apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase-check

  annotations:
    prueba: "1"
    argocd.argoproj.io/hook: PreSync
    # argocd.argoproj.io/hook-delete-policy: BeforeHookCreation, HookSucceeded

spec:
  backoffLimit: 0

  template:
    spec:
      replicas: 2
      restartPolicy: Never

      containers:
        - name: liquibase

          image: liquibase/liquibase:5.0

          command:
            - sh
            - -c

          args:
            - |
              echo "=== PreSync iniciado ==="
              liquibase --version
              sleep 15
              echo "=== PreSync finalizado ==="